export { default as TachesDnd } from './taches/taches-dnd/TachesDnd'
export { default as TachesEdition } from './taches/taches-edition/TachesEdition'
export { default as TrainProgressBar } from './taches/train-progress-bar/TrainProgressBar'

export { default as RecompensesEdition } from './recompenses/recompenses-edition/RecompensesEdition'
export { default as SelectedRewardFloating } from './recompenses/selected-reward-floating/SelectedRewardFloating'

export { default as AccountStatusBadge } from './shared/AccountStatusBadge'
export { default as AvatarProfil } from './shared/avatar-profil/AvatarProfil'
export { default as BaseCard } from './shared/card/base-card/BaseCard'
export { default as EditionCard } from './shared/card/edition-card/EditionCard'
export { default as TableauCard } from './shared/card/tableau-card/TableauCard'
export { default as DemoSignedImage } from './shared/demo-signed-image/DemoSignedImage'
export { default as EditionList } from './shared/edition-list/EditionList'
export { default as ItemForm } from './shared/forms/ItemForm'
export { default as InputWithValidation } from './shared/input-with-validation/InputWithValidation'
export { default as LangSelector } from './shared/lang-selector/LangSelector'
export { default as Layout } from './shared/layout/Layout'
export { default as Modal } from './shared/modal/Modal'
export { default as ModalAjout } from './shared/modal/modal-ajout/ModalAjout'
export { default as ModalCategory } from './shared/modal/modal-category/ModalCategory'
export { default as ModalConfirm } from './shared/modal/modal-confirm/ModalConfirm'
export { default as ModalQuota } from './shared/modal/modal-quota/ModalQuota'
export { default as Navbar } from './shared/navbar/Navbar'
export { default as PageTransition } from './shared/page-transition/PageTransition'
export { PermissionsDebug } from './shared/permissions-debug/PermissionsDebug'
export { PermissionsTest } from './shared/permissions-test/PermissionsTest'
export { default as ProtectedRoute } from './shared/protected-route/ProtectedRoute'
export { default as QuotaIndicator } from './shared/QuotaIndicator'
export { default as Separator } from './shared/separator/Separator'
export { default as SignedImage } from './shared/signed-image/SignedImage'
export { default as ThemeToggle } from './shared/theme-toggle/ThemeToggle'

export { default as PersonalizationModal } from './modals/PersonalizationModal'
export { SignupPromptModal } from './modals/SignupPromptModal'
export {
    FeatureGate,
    PremiumFeatureGate
} from './shared/feature-gate/FeatureGate'
export { default as ModalRecompense } from './shared/modal/modal-recompense/ModalRecompense'

export { default as Button } from './ui/button/Button'
export { default as ButtonClose } from './ui/button/button-close/ButtonClose'
export { default as ButtonDelete } from './ui/button/button-delete/ButtonDelete'
export { default as Checkbox } from './ui/checkbox/Checkbox'
export { default as FloatingPencil } from './ui/floating-pencil/FloatingPencil'
export { default as ImagePreview } from './ui/image-preview/ImagePreview'
export { default as Input } from './ui/input/Input'
export { default as Loader } from './ui/loader/Loader'
export { default as PasswordChecklist } from './ui/password-checklist/PasswordChecklist'
export { default as Select } from './ui/select/Select'
export { default as Toast } from './ui/toast/Toast'

export { default as CookieBanner } from './consent/CookieBanner'
export { default as CookiePreferences } from './consent/CookiePreferences'
export { default as Footer } from './footer/Footer'
export { default as LegalMarkdown } from './legal-markdown/LegalMarkdown'
export { default as DeleteAccountGuard } from './settings/DeleteAccountGuard'
export { default as DeleteAccountModal } from './settings/DeleteAccountModal'
export { default as SubscribeButton } from './subscribe-button/SubscribeButton'
export { default as UserMenu } from './user-menu/UserMenu'

// Composants d'administration
export { default as AccountManagement } from './admin/AccountManagement'
export { default as QuotaManagement } from './admin/QuotaManagement'

