// Re-export legal content (Next.js compatible)
export {
  MENTIONS_LEGALES_MD,
  CGU_MD,
  CGV_MD,
  POLITIQUE_CONFIDENTIALITE_MD,
  POLITIQUE_COOKIES_MD,
  LEGAL_NOTICES_EN_MD,
  TERMS_OF_USE_EN_MD,
  TERMS_OF_SALE_EN_MD,
  PRIVACY_POLICY_EN_MD,
  COOKIE_POLICY_EN_MD,
} from './legal-content'
